name: local_notes_app
description: "A simple local notes application using Flutter and SQLite."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
